server.port: 7001
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db
  auto-index-creation: true

logging:
  level:
    root: INFO
    com.lin: DEBUG

---
spring.profiles: docker

server.port: 8080

spring.data.mongodb.host: mongodb
